### ISSUE TITLE
Help me pls

### ISSUE THREAD

**Issue by slossgaming** [sentanos/roblox-js-server#10]
Exactly how can you execute this in PHP? I am attempting to use the message bot, but don't know what to do, Would you mind putting an example.
Edit2:
I'm asking how can I use this in PHP? Meaning how may I execute it thru my code? I already have Heroku running it. I'm not dumb. Not how do I do this in PHP? I'm simply asking how can I execute this in PHP, as I want to make a message bot.

**Comment by sentanos** [comment]
I do not understand your question, please clarify. Are you talking about POSTing from PHP or something?

**Comment by slossgaming** [comment]
That's exactly what I'm asking!

**Comment by sentanos** [comment]
This is already a server, instead of trying to use a second server to activate the first one you should edit the files themselves to do what you want. I do not have time to teach you what to do in PHP, the documentation is already very clear on what requests should look like and if you want to use it you would use something such as cURL to set up the request.

**Comment by sentanos** [comment]
Please see #17
