### ISSUE TITLE
Contribution towards the project (NOT AN ISSUE)

### ISSUE THREAD

**Issue by SparkleOff** [sentanos/roblox-js-server#16]
I thought this would be useful towards your project since a lot of people are converting from your PHP project to your NodeJS project.  It is a PHP class, all the same functions that the LUA has, it has all been tested and it works. It is a very easy setup in PHP, and uses a PHP class to make it easier for the person to use. Sorry for being a dummy before, i am famous for speaking before i actually think about it.

PHP Class:
http://pastebin.com/fhe5QDbe

PHP Test Code:
http://pastebin.com/SaWLv04v

Thank you so much @sentanos for your participation in the community with this code. It has been a great help for me and i am sure a lot of other developers.

**Comment by sentanos** [comment]
Thank you for this contribution, you may create a pull request to make it more permanent. I still stress that instead of proxying through PHP people should call functions directly through the code itself, either based off functions already in the module or off of the core module [roblox-js](https://github.com/sentanos/roblox-js) but I understand that some people want to work with a more familiar.
