### ISSUE TITLE
Failing to do anything.

### ISSUE THREAD

**Issue by Zlecktov** [sentanos/roblox-js-server#2]
I just get the error messages when trying to use this.  I know it is setup properly, because I am getting the error messages inside the server script.  My password is correct and my username for sure is right.   And my key is easy to remember.

**Comment by Zlecktov** [comment]
Shout failed, verify login, permissions, and message

**Comment by Zlecktov** [comment]
All of which should be operational

**Comment by oreagon** [comment]
I'm having the same issue right now, and whats worse is I had everything working just a couple days ago.

**Comment by DevelopingCodes** [comment]
I have the same issue and it's a problem because I have a group that operates on it and needs to work really badly.

**Comment by DevelopingCodes** [comment]
@sentanos

**Comment by sentanos** [comment]
This issue has been confirmed and will be fixed as soon as possible.

**Comment by oreagon** [comment]
Thanks sentanos :D

**Comment by sentanos** [comment]
The issue was due to ROBLOX removing the login API I was originally using and is not due to this project but the dependency module. I have fixed that bug and more information is available [here](https://github.com/sentanos/roblox-js/commit/16e29957103753a4d48e6d76f3fa37c259f43aae). 

Because it was due to the dependency you do not have to update your actual server files but only the dependencies. If you are using heroku rebuild your app by submitting an empty commit with the following commands:
```bash
cd "path/to/app (drag it in like in the tutorial)"
heroku config:set NODE_MODULES_CACHE=false
git commit --allow-empty -m "Rebuild"
git push heroku master
heroku config:unset NODE_MODULES_CACHE
```
and it should update the dependency. I apologize for the inconvenience.

Please reply here again to confirm the issue has been fixed and I will close it.

**Comment by DevelopingCodes** [comment]
@sentanos I can confirm that it does work now, however I tried running those commands you listed, but I couldn't get it to work or I did it improperly.

Regardless, I made a new app for it and I can confirm that it works. Thanks!

**Comment by Zlecktov** [comment]
Works properly.  Thanks so much.
