### ISSUE TITLE
Cannot GET

### ISSUE THREAD

**Issue by The-Tarkol** [sentanos/roblox-js-server#30]
I'm sure it's an error on my part, but recently the bot broke. I read through the issues and found I needed to update the libraries, which I did. It's still not working, however, and when I try to navigate to the page for the bot I get the error "Cannot GET /". Thanks in advance for your help, you've done a fantastic job.

**Comment by slossgaming** [comment]
Are you using CMD line/Server or are you using a host like Heroku? Also whats your console saying?

**Comment by sentanos** [comment]
"Cannot GET /" is not an error, if you are viewing the site from a browser it will always show that (since the server is supposed to be accessed from in-game). 

If you are sure you updated you need to show your actual logs. If you are hosting on Heroku do the following: go to heroku.com and log in, then go to your server and click the three dots in the upper right hand corner and click "View Logs" then do the same thing and click "Restart All Dynos" and post the output of the logs here.

**Comment by The-Tarkol** [comment]
I was using Heroku, updated via command line. Bot account was managed by multiple people, and someone changed the password, which is why it didn't work. All good now, thank you!
