### ISSUE TITLE
HTTP 404 Error

### ISSUE THREAD

**Issue by SamTheMan1456** [sentanos/roblox-js-server#46]
Hello,

I recently made it so you walk over a brick and get promoted. There's been HTTP 404 error 1.1/1.2 or something. The account info is right and 2 factor authentication is off. Help.

**Comment by sentanos** [comment]
Are you using heroku? What is the link to the app? Are you sure you completed the setup correctly?

**Comment by SamTheMan1456** [comment]
I am using my own web server, it was happening on Heroku so I decided to use my own web server. All I did was drag the files into it and specify the location, is that all or is there another reason to this error being produced?

**Comment by sentanos** [comment]
...Did you not run it with `node server.js`?

**Comment by SamTheMan1456** [comment]
No, I just dragged my files. Was I supposed to run that in the first place?

**Comment by sentanos** [comment]
If you are running this on your own server you should know what you're doing, because it is not as simple. You have to change the port, properly run it after installing node, and use a process manager such as pm2. If you don't know how to do these, either learn or just use heroku. Heroku works fine if you set it up correctly, but many people make some mistake during the setup process.

**Comment by SamTheMan1456** [comment]
I've been using Heroku and setup is a success, but I get 404 errors on that too. Do I have to use any other commands after installation on heroku?

**Comment by sentanos** [comment]
Take a screenshot of the heroku app when you visit the URL in your browser.

**Comment by SamTheMan1456** [comment]
[https://gyazo.com/37950b67016c969130fc2d7c738c43a8](url)

**Comment by sentanos** [comment]
Incorrect setup.

**Comment by sentanos** [comment]
To be clear OP forgot to do step 9 `git push heroku master` and also left 2 step verification on
