### ISSUE TITLE
Failing to Promote

### ISSUE THREAD

**Issue by DevelopingCodes** [sentanos/roblox-js-server#5]
The bot stopped doing the promotion action. I have not updated the place and it's worked 2 days ago.

I looked if there was an update, but there was no update that was extremely recent.

[Here's an image of the error.](http://prntscr.com/dimx48)

I do not know if the other functions work, so if anyone else wants to bring that out and confirm. Also, please confirm if you are having the same issue to make sure it's not just me. Thanks :)

@sentanos

**Comment by sentanos** [comment]
I cannot replicate the issue. Since you claim nothing has been updated since it last worked I can only assume that it is a problem with your user permissions. Please make absolutely sure that you are able to make the exact same rank change you are trying to make on the scripts when using the actual user. If you want me to take a look for you I need:
- The exact way you are calling the function
- A picture of the permission settings of your group
- The exact roles and ranks of the player having their rank changed and the player doing the rank change
- Verification that you are actually logged in (confirm username and password are correct, no 2-step, etc.)
  - Try using other functions and see what happens

**Comment by DevelopingCodes** [comment]
I didn't touch anyhting the whole day and I just test-ran it, it seems to have worked.

Probably something came in the way. Thanks though! Sorry for this.
