### ISSUE TITLE
Cannot Get /

### ISSUE THREAD

**Issue by crabbynick4** [sentanos/roblox-js-server#58]
I tried and got the system to work. I had to change it once due to something so I remade it without updating I just remade it as if it was brand new. Now, no matter what heroku account, or how many times I download this repository I have this error http://prntscr.com/h689uc. The website I am using currently that has this error is https://sg-rank-bot-system.herokuapp.com/. Please help as soon as possible, I have been doing this literally probably 3 hours.

**Comment by sentanos** [comment]
This is not an error. If it says “Cannot GET /“ that means it was setup correctly.

**Comment by crabbynick4** [comment]
I did everything correct, I downloaded the repository and edited and followed everything four times, a friend had a faster button too to automatically do it, it looks like a possible problem in the coding.

**Comment by sentanos** [comment]
Let me clarify again: "Cannot GET /" **IS NOT AN ERROR**
It is what is supposed to happen when you visit from a browser because the server is not meant to be used from a browser but from a ROBLOX server.
Again: **IT IS NOT AN ERROR WITH THE SERVER. THERE IS NO ERROR HERE**

If you have an error to show in the ROBLOX console you can post that. What you have posted right now is not an error.
